--- 
title: "HandBook for a Pediatrician"
author: "Pediatrician"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: doc4child/doc4child
description: "This is a Handbook for a Pediatrician"
---

# Preface {-}

This is a _Pocket Book_ for **information purpose only**


## Term of Use {-}

All clinical information published by doc4child.com on this website is for informational purposes only. Medical field is constantly evolving and there are conflicting data and information published by various sources. The readers, heathcare providers, patients and consumers should confirm the information contained herein with other sources and review the information with a qualified physician. The information is not intended to replace medical advice offered by qualified physicians. You should not rely on information received by this website for medical, legal or financial decisions. Should you decide to act upon any information on this website, you do so at your own risk. Each patient is unique and this information may not be applicable to patient's specific situation. While the information on this website has been verified to the best of our abilities, we cannot guarantee that there are no mistakes or errors. The doc4child.com will not be liable for any direct, indirect, consequential, special, exemplary or other damages arising therefrom.
